openapi: 3.0.0
info:
  title: Reservation API
  version: 1.0.0
paths:
  /reservation:
    post:
      summary: Create a reservation
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                operationId:
                  type: string
                  example: "0123456789"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - ok
                      - ng
                  id:
                    type: string
                    example: "R001"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - ng
