openapi: 3.0.0
info:
  title: 認高喜笑助整形外科予約システム
  version: 1.0.0
paths:
  /reservation:
    post:
      summary: Create a reservation
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                operationId:
                  type: string
                  example: "0123456789"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - ok
                      - ng
                  numberedTicket:
                    type: object
                    properties:
                      imageUrl:
                        type: string
                        format: uri
                        example: "https://example.com/1695452728.png"
                      id:
                        type: string
                        example: "R001"
                  message:
                    type: string
                    example: "Internal Server Error"
