openapi: 3.0.0
info:
  title: 病院検索・予約システム
  version: 1.0.0
paths:
  /search:
    get:
      summary: クリニックを検索する
      operationId: searchClinic
      parameters:
        - name: department
          in: query
          description: 科の種類
          required: true
          schema:
            type: string
            enum:
              - orthopedics
              - internalMedicine
              - psychosomaticMedicine
        - name: station
          in: query
          description: 駅の名前
          required: true
          schema:
            type: string
            enum:
              - gotano
              - kitasenju
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  clinicId:
                    type: string
                    example: "C001"

  /reservation:
    post:
      summary: 整理券を発行する
      operationId: issueNumberedTicket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clinicId:
                  type: string
                  example: "C001"
                patientInfo:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "足立太郎"
                    nameKana:
                      type: string
                      example: "アダチタロウ"
                    tel:
                      type: string
                      pattern: '^[0-9]{10,11}$'
                      example: "09012345678"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - ok
                      - ng
                  clinic:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "C001"
                      name:
                        type: string
                        example: "認高喜笑助整形外科"
                  numberedTicket:
                    type: object
                    properties:
                      imageUrl:
                        type: string
                        format: uri
                        example: "https://example.com/R001.png"
                      id:
                        type: string
                        example: "R001"
                  message:
                    type: string
                    example: "Internal Server Error"
