openapi: 3.0.0
info:
  title: 認高喜笑助整形外科予約システム
  version: 1.0.0

paths:
  /reservation:
    post:
      summary: 整理券を発行する
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patientInfo:
                  type: object
                  properties:
                    name:
                      type: string
                    nameKana:
                      type: string
                    tel:
                      type: string
                operationId:
                  type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - ok
                      - ng
                  numberedTicket:
                    type: object
                    properties:
                      image:
                        type: string
                      id:
                        type: string
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - ng
                  message:
                    type: string
